blog/urls.py
from django.urls import path

from .views import *

app_name = 'blog'
urlpatterns = [
    path('', homepage, name='home'),

    path('search/', search, name='search'),
    path('search/result/', searchResults, name='searchresult'),

    path('upload/', uploadPost, name='uploadpost'),

    path('category/', category, name='category'),
    path('category/<str:category>/', categoryDetail, name='categorydetial'),

    path('view/<str:pk>/', viewPost, name="viewpost"),
    path('like/<str:pk>/', likePost, name="likepost"),
    path('update/<str:pk>/', updatePost, name="updatepost"),
    path('remove/<str:pk>/', deletePost, name="deletepost"),

    path('profile/', viewMyProfile, name='viewmyprofile'),
    path('profile/settings/', editProfile, name='editprofile'),
    path('profile/view/<str:pk>/', viewOtherProfile, name='viewotherprofile'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('blog.urls')),
    path('register/', include('registration.urls')),
    
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration/urls.py
from django.urls import path
from . import views

app_name = 'registration'
urlpatterns = [
    path('', views.homepage, name='homepage'),

    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    
    path('signup/', views.user_signup, name='signup'),
]

blog/models.py
from django.db import models

from django.core.validators import MaxLengthValidator, MinLengthValidator
from django.contrib.auth.models import User

# from ckeditor.fields import RichTextField


class UserProfile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)

    first_name = models.CharField(max_length=50, null=True)
    middle_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=50, null=True)
    email = models.EmailField(null=True)
    birthdate = models.DateField(null=True)

    GENDER_CHOICES = (
    		('M', 'Male'),
    		('F', 'Female'),
    	)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, null=True)

    profile_picture = models.ImageField(default='profile_images/default.png', null=True, upload_to="profile_images/")

    bio = models.TextField(null=True, blank=True, validators=[MaxLengthValidator(150), MinLengthValidator(10)])

    date_joined = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)


class Category(models.Model):
    name = models.CharField(max_length=70, null=True)

    def __str__(self):
        return self.name


class BlogPost(models.Model):
    author = models.ForeignKey(UserProfile, null=True, on_delete=models.SET_NULL)

    title = models.CharField(max_length=200, null=True)
    short_description = models.TextField(null=True, validators=[MaxLengthValidator(200), MinLengthValidator(30)])

    category = models.ForeignKey(Category, null=True, on_delete=models.CASCADE)
    related_image = models.ImageField(default='blog.jpg', upload_to="blog_images/", null=True)
    content = models.TextField()
    likes = models.ManyToManyField(UserProfile, related_name='likes', blank=True)

    date_added = models.DateTimeField(auto_now_add=True, null=True)

    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return "%s | %s " % (self.title, self.author)

class Comment(models.Model):
    user = models.ForeignKey(UserProfile, null=True, on_delete=models.CASCADE)

    post = models.ForeignKey(BlogPost, null=True, related_name="comments", on_delete=models.CASCADE)
    body = models.TextField()

    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s - %s" % (self.post.title, self.user)


"""
I need to create a blog model so it would have 
* A header
* The post
* A comment session
* The author
* Date published 
* Related images
"""

blog/forms.py
from django import forms
from django.forms import ModelForm, Textarea

# from ckeditor.fields import RichTextField

from .models import *
from .dates import *

class DatePicker(forms.DateInput):
	input_type = 'date'
		

class EditProfileForm(ModelForm):
	first_name = forms.CharField(
        widget=forms.TextInput(attrs={
        	'placeholder': 'First name' , 
        	'class': 'form-control',
        	})
        )
	middle_name = forms.CharField(
		required=False,
        widget=forms.TextInput(attrs={
        	'placeholder': 'Middle name' , 
        	'class': 'form-control',
        	})
        )
	last_name = forms.CharField(
        widget=forms.TextInput(attrs={
        	'placeholder': 'Last name', 
        	'class': 'form-control',
        	})
        )
	email = forms.EmailField(
        widget=forms.EmailInput(attrs={
        	'placeholder': 'Email', 
        	'class': 'form-control',
        	})
        )

	birthdate = forms.DateField(widget=forms.SelectDateWidget(years=BIRTH_YEARS))

	bio = forms.CharField(
		widget=forms.Textarea(attrs={
			'class': 'form-control', 
			'rows': 3, 
			'placeholder': 'Write a little about your self!'
			})
		)

	GENDER_CHOICES = (
    		('M', 'Male'),
    		('F', 'Female'),
    	)
	gender = forms.ChoiceField(
		label="",
		choices=GENDER_CHOICES,
        widget=forms.RadioSelect(),
        )

	class Meta:
		model = UserProfile
		fields = '__all__'
		exclude = ['user']


class BlogPostForm(ModelForm):
	title = forms.CharField(
		label="",
        widget=forms.TextInput(attrs={
        	'placeholder': 'Blog Title', 
        	'class': 'form-control'})
        )
	short_description = forms.CharField(
		label="",
		widget=forms.Textarea(attrs={
			'class': 'form-control', 
			'rows': 2, 
			'placeholder': 'Write a short description about your post'
			})
		)
	content = forms.CharField(
		label="",
		widget=forms.Textarea(attrs={
			'class': 'form-control', 
			'rows': 8, 
			'placeholder': 'Your content goes here!'
			})
		)

	class Meta:
		model = BlogPost
		fields = '__all__'
		exclude = ['author', 'likes']


class CommentForm(ModelForm):
	body = forms.CharField(
		widget=forms.Textarea(attrs={
			'class': 'form-control', 
			'rows': 3, 
			'placeholder': 'Join the discussion and leave a comment!'
			})
		)
	class Meta:
		model = Comment
		fields = ['body']

	
class SearchForm(ModelForm):
	author = forms.ModelChoiceField(
		queryset=UserProfile.objects.all(),
		label='',
		required=False,
		)
	title = forms.CharField(
		label="",
		required=False,
        widget=forms.TextInput(attrs={
        	'placeholder': 'Title', 
        	'class': 'form-control'})
        )
	short_description = forms.CharField(
		label="",
		required=False,
        widget=forms.TextInput(attrs={
        	'placeholder': 'Short description', 
        	'class': 'form-control'})
        )
	category = forms.ModelChoiceField(
		queryset=Category.objects.all(),
		label='',
		required=False,
		)
	class Meta:
		model = BlogPost
		fields = '__all__'
		exclude = ['likes', 'related_image', 'date_added', 'content']

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404

from django.contrib.auth.decorators import login_required

from django.contrib import messages

from django.db.models import Q

from .forms import *
from .models import *
from .decorators import *
from .filters import *

# Create your views here.

def homepage(request):
	blogs = BlogPost.objects.all()

	last_post = blogs.order_by('date_added')[0]
	latest_ten_blogs = blogs.order_by('-date_added')[0:10]

	first_five = latest_ten_blogs[0:5]
	second_five = latest_ten_blogs[5:10]

	blog_filter = BlogPostFilter(request.GET, queryset=blogs)

	context = {
		'last_post': last_post,
		'blogs': blogs,
		'first_five': first_five,
		'second_five': second_five,
		'filter': blog_filter,
	}

	return render(request, 'blog/index.html', context)

# i need to create a featured attribute in my model so it would show featured blogs

@only_logged_in_users
@login_required(login_url='registration:login')
@unregistered_user
def uploadPost(request):
	form = BlogPostForm()
	author = request.user.userprofile

	if request.method == 'POST':
		form = BlogPostForm(request.POST, request.FILES)
		if form.is_valid():
			BlogPost.objects.create(author=author, **form.cleaned_data)
			return redirect('blog:view')
			
	context = {
		'form': form
	}
	return render(request, 'blog/upload_post.html', context)


def viewPost(request, pk):
	blog = BlogPost.objects.get(pk=pk)
	form = CommentForm()

	if request.method == 'POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			Comment.objects.create(post=blog, user=request.user.userprofile, **form.cleaned_data)
			return redirect('blog:viewpost', pk=pk)

	context = {
		'blog': blog,
		'form': form,
		'total_likes': blog.total_likes(),
	}

	return render(request, 'blog/view_post.html', context)

@only_logged_in_users
def likePost(request, pk):
	post = get_object_or_404(BlogPost, id=request.POST.get('blog_id'))
	post.likes.add(request.user.userprofile)
	return redirect('blog:viewpost', pk=pk)

@unregistered_user
@login_required(login_url='registration:login')
def updatePost(request, pk):
	blog = BlogPost.objects.get(pk=pk)
	form = BlogPostForm(instance=blog)

	if request.method == 'POST':
		form = BlogPostForm(request.POST, request.FILES, instance=blog)
		if form.is_valid():
			form.save()

			messages.info(request, 'You edited your post!')

			return redirect('blog:viewpost', pk=pk)

	context = {
		'form': form,
		'blog': blog
    }

	return render(request, 'blog/update_post.html', context)

@restriction_of_delete_from_unauthenticated_user
@restriction_of_delete
def deletePost(request, pk):
	item = BlogPost.objects.get(pk=pk)

	if request.method == 'POST':
		item.delete()
		return redirect('blog:home')

	context = {
		'item': item,
    }

	return render(request, 'blog/delete_post.html', context)

@only_logged_in_users
@login_required(login_url='registration:login')
def viewMyProfile(request):
	user = request.user.userprofile
	user_posts = user.blogpost_set.all()

	user_details = UserProfile.objects.get(id=user.id)

	context = {
		'user': user,
		'user_posts': user_posts,
		'user_details': user_details,
	}
	return render(request, 'blog/self_profile_view.html', context)

@unregistered_user
def viewOtherProfile(request, pk):
	user = get_object_or_404(UserProfile, pk=pk)

	context = {
		'user': user
	}
	return render(request, 'blog/user_profile_view.html', context)
# i would download some template to render a user details and then the blogs they have posted

@only_logged_in_users
@login_required(login_url='registration:login')
def editProfile(request):
	user = request.user.userprofile
	form = EditProfileForm(instance=user)

	if request.method == 'POST':
		form = EditProfileForm(request.POST, request.FILES, instance=user)
		if form.is_valid():
			if form.cleaned_data['profile_picture'] == 'profile_images/default.png': 
				if form.cleaned_data['profile_picture'] == 'profile_images/default.png' or 'profile_images/female.png' or 'profile_images/male.png':
					if form.cleaned_data['gender'] == 'F':
						request.user.userprofile.profile_picture = 'profile_images/female.png'
					elif form.cleaned_data['gender'] == 'M':
						request.user.userprofile.profile_picture = 'profile_images/male.png'
			form.save()
			return redirect('blog:viewmyprofile') 

	context = {
		'form': form
	}
	return render(request, 'blog/user_profile_settings.html', context)

def search(request):
	form = SearchForm()

	context = {
		'form': form
	}

	return render(request, 'blog/search.html', context)

def searchResults(request):
	blogs = BlogPost.objects.all()
	blog_filter = BlogPostFilter(request.GET, queryset=blogs)
	blogs = blog_filter.qs

	for item in request.GET:
		if request.GET[item] == '':
			print('sorry')

	context = {
		'blogs': blogs,
	}
	return render(request, 'blog/search_results.html', context)


def category(request):
	news = Category.objects.get(name='news')
	sport = Category.objects.get(name='sport')
	health = Category.objects.get(name='health')
	fashion = Category.objects.get(name='fashion')
	entertainment = Category.objects.get(name='entertainment')

	news_posts = news.blogpost_set.all()
	sport_posts = sport.blogpost_set.all()
	health_posts = health.blogpost_set.all()
	fashion_posts = fashion.blogpost_set.all()
	entertainment_posts = entertainment.blogpost_set.all()

	context = {
		'news': news_posts,
		'sports': sport_posts,
		'health': health_posts,
		'fashion': fashion_posts,
		'entertainment': entertainment_posts,

		'news_category': news,
		'sports_category': sport,
		'health_category': health,
		'fashion_category': fashion,
		'entertainment_category': entertainment,
	}
	return render(request, 'blog/categories.html', context)


def categoryDetail(request, category):
	category = Category.objects.get(name=category)
	blog_related_by_category = get_list_or_404(BlogPost, category=category)

	context = {
		'blogs': blog_related_by_category,
		'category': category,
	}

	return render(request, 'blog/category_detail.html', context)

blog/templates/blog/categories.html
{% extends 'blog/base.html' %}

{% load static %}
{% load humanize %}

{% block stylesheet %}
    <link href="{% static 'css/footer.css' %}" rel="stylesheet"/>
{% endblock %}


{% block content %}
	{% include 'blog/navbar.html' %}

	{% if news %}
		<h2 class="text-center font-weight-bold my-1"><a class="text-reset text-decoration-none" href="{% url 'blog:categorydetial' news_category %}">News</a></h2>
		<div class="row mx-3 my-2">
		{% for blog in news %}
			<div class="col-sm-4">
				<div class="card mb-4">
			        <a href="{% url 'blog:viewpost' blog.id %}"><img class="card-img-top" src="{{ blog.related_image.url }}" alt="{{ blog.title }} photo" /></a>
			        
			        <div class="card-body">

			            <div class="small text-muted">{{ blog.date_added | naturaltime | naturalday }}</div>

			            <h2 class="card-title h4">{{ blog.title }}</h2>

			            {% autoescape off %}
			            <p class="card-text">{{ blog.short_description }}</p>
			            {% endautoescape %}

			            <a class="btn btn-primary" style="text-decoration: none;" href="{% url 'blog:viewpost' blog.id %}">Read more →</a>

			        </div>
			    </div>
			</div>
	    {% endfor %}
		</div>
	{% endif %}

	{% if sports %}
		<h2 class="text-center font-weight-bold my-1"><a class="text-reset text-decoration-none" href="{% url 'blog:categorydetial' sports_category %}">Sport</a></h2>
		<div class="row mx-3 my-2">
		{% for blog in sports %}
			<div class="col-sm-4">
				<div class="card mb-4">
			        <a href="{% url 'blog:viewpost' blog.id %}"><img class="card-img-top" src="{{ blog.related_image.url }}" alt="{{ blog.title }} photo" /></a>
			        
			        <div class="card-body">

			            <div class="small text-muted">{{ blog.date_added | naturaltime | naturalday }}</div>

			            <h2 class="card-title h4">{{ blog.title }}</h2>

			            {% autoescape off %}
			            <p class="card-text">{{ blog.short_description }}</p>
			            {% endautoescape %}

			            <a class="btn btn-primary" style="text-decoration: none;" href="{% url 'blog:viewpost' blog.id %}">Read more →</a>

			        </div>
			    </div>
			</div>
	    {% endfor %}
		</div>
	{% endif %}

	{% if health %}
		<h2 class="text-center font-weight-bold my-1"><a class="text-reset text-decoration-none" href="{% url 'blog:categorydetial' health_category %}">Health</a></h2>
		<div class="row mx-3 my-2">
		{% for blog in health %}
			<div class="col-sm-4">
				<div class="card mb-4">
			        <a href="{% url 'blog:viewpost' blog.id %}"><img class="card-img-top" src="{{ blog.related_image.url }}" alt="{{ blog.title }} photo" /></a>
			        
			        <div class="card-body">

			            <div class="small text-muted">{{ blog.date_added | naturaltime | naturalday }}</div>

			            <h2 class="card-title h4">{{ blog.title }}</h2>

			            {% autoescape off %}
			            <p class="card-text">{{ blog.short_description }}</p>
			            {% endautoescape %}

			            <a class="btn btn-primary" style="text-decoration: none;" href="{% url 'blog:viewpost' blog.id %}">Read more →</a>

			        </div>
			    </div>
			</div>
	    {% endfor %}
		</div>
	{% endif %}

	{% if fashion %}
		<h2 class="text-center font-weight-bold my-1"><a class="text-reset text-decoration-none" href="{% url 'blog:categorydetial' fashion_category %}">Fashion</a></h2>
		<div class="row mx-3 my-2">
		{% for blog in fashion %}
			<div class="col-sm-4">
				<div class="card mb-4">
			        <a href="{% url 'blog:viewpost' blog.id %}"><img class="card-img-top" src="{{ blog.related_image.url }}" alt="{{ blog.title }} photo" /></a>
			        
			        <div class="card-body">

			            <div class="small text-muted">{{ blog.date_added | naturaltime | naturalday }}</div>

			            <h2 class="card-title h4">{{ blog.title }}</h2>

			            {% autoescape off %}
			            <p class="card-text">{{ blog.short_description }}</p>
			            {% endautoescape %}

			            <a class="btn btn-primary" style="text-decoration: none;" href="{% url 'blog:viewpost' blog.id %}">Read more →</a>

			        </div>
			    </div>
			</div>
	    {% endfor %}
		</div>
	{% endif %}

	{% if entertainment %}
		<h2 class="text-center font-weight-bold my-1"><a class="text-reset text-decoration-none" href="{% url 'blog:categorydetial' entertainment_category %}">Entertainment</a></h2>
		<div class="row mx-3 my-2">
		{% for blog in entertainment %}
			<div class="col-sm-4">
				<div class="card mb-4">
			        <a href="{% url 'blog:viewpost' blog.id %}"><img class="card-img-top" src="{{ blog.related_image.url }}" alt="{{ blog.title }} photo" /></a>
			        
			        <div class="card-body">

			            <div class="small text-muted">{{ blog.date_added | naturaltime | naturalday }}</div>

			            <h2 class="card-title h4">{{ blog.title }}</h2>

			            {% autoescape off %}
			            <p class="card-text">{{ blog.short_description }}</p>
			            {% endautoescape %}

			            <a class="btn btn-primary" style="text-decoration: none;" href="{% url 'blog:viewpost' blog.id %}">Read more →</a>

			        </div>
			    </div>
			</div>
	    {% endfor %}
		</div>
	{% endif %}

{% include 'blog/footer.html' %}
   
{% endblock %}

blog/templates/blog/delete_post.html
{% extends 'blog/base.html' %}

{% load static %}

{% block content %}
    <br>

    <div class=" text-center">
        <p>Are you sure you want to delete <b>{{ item.title }}</b>?</p>
        <form action="{% url 'blog:deletepost' item.id %}" method="POST">

            {% csrf_token %}
            
            <a class="btn btn-warning" href="{% url 'blog:viewpost' item.id %}">Cancel</a>

            <button type="submit" class="btn btn-danger">Yes, i'm sure</button>
        </form>
    </div>
        
    
{% endblock %}

blog/templates/blog/navbar.html
{% load static %}

<style>
  #hello-message {
    font-weight: 18px;
    color: #fff;
    margin-right: 10px;
  }
  #logout-url {
    text-decoration: none;
    color: #6186d5;
  }
  #signup-url {
    text-decoration: none;
    color: #6186d5;
  }
  #navbar {
    background-color: #141d2a
  }
  #url {
    color: #6186d5;
  }
</style>

 <nav id="navbar" class="navbar navbar-expand-sm ">

            <div class="container">
              {% if request.user.is_authenticated %}
                  <span class="navbar-brand" id="hello-message"><a class="text-capitalize text-reset text-decoration-none" href="{% url 'blog:viewmyprofile' %}">Hello, {{ request.user.username }}</a></span>
              {% else %}
                <span id="hello-message" class="navbar-brand">Hello Guest</span>
              {% endif %}

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">

                      {% if request.user.is_authenticated %}

                        <li class="nav-item"><a class="nav-link active" id="url" href="{% url 'blog:home' %}">Home</a></li>
                         <li class="nav-item"><a class="nav-link" id="url" href="{% url 'blog:category' %}">Category</a></li>
                        <li class="nav-item"><a class="nav-link" id="url" href="{% url 'blog:uploadpost' %}">Upload</a></li>
                        <li class="nav-item"><a class="nav-link" id="logout-url" aria-current="page" href="{% url 'registration:logout' %}">Logout</a></li>

                        {% else %}
                        
                        <li class="nav-item"><a class="nav-link active" id="url" href="{% url 'blog:home' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link active" id="url" href="{% url 'blog:category' %}">Categories</a></li>
                        <li class="nav-item"><a class="nav-link active" id="url" href="{% url 'registration:login' %}">Login</a></li>
                        <li class="nav-item"><a class="nav-link active" id="signup-url" href="{% url 'registration:signup' %}">Signup</a></li>

                      {% endif %}
                    </ul>
                </div>

            </div>
            
        </nav>



    

blog/templates/blog/search.html
{% extends 'blog/base.html' %}

{% load static %}

{% block stylesheet %}
    <link href="{% static 'css/footer.css' %}" rel="stylesheet"/>
{% endblock %}

{% block content %}

{% include 'blog/navbar.html' %}
<div class="my-3 mx-3">
	<form method="GET" action="{% url 'blog:searchresult' %}">

    <div class="row">
      <div class="col-sm-2">
        <div class="card card-body bg-dark">
          <div class="d-flex flex-column align-items-center text-center">
            {{ form.author }}
          </div>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="card card-body bg-dark">
          <div class="d-flex flex-column align-items-center text-center">
            {{ form.title }}
          </div>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="card card-body bg-dark">
          <div class="d-flex flex-column align-items-center text-center">
            {{ form.short_description }}
          </div>
        </div>
      </div>

      <div class="col-sm-2">
        <div class="card card-body bg-dark">
          <div class="d-flex flex-column align-items-center text-center">
            {{ form.category }}
          </div>
        </div>
      </div>

      <div>
        <button type="submit" class="btn btn-primary">Search</button>
      </div>
    </div>
		
	</form>
</div>
{% include 'blog/footer.html' %}
	
{% endblock %}

<!-- I need to download a search template and i need to put the footer below the page so it does'nt loook awkward! -->

blog/templates/blog/search_results.html
{% extends 'blog/base.html' %}

{% load static %}

{% block content %}

{% if blogs %}
<div class="card card-body">
  <table class="table table-sm">
    <tr>
      <th>Author</th>
      <th>Title</th>
      <th>Content</th>
    </tr>
    {% for blog in blogs %}
    <tr>
      <td>{{ blog.author }}</td>
      <td>{{ blog.title }}</td>
      <td>{{ blog.content }}</td>
    </tr>
    {% endfor %}
  </table>
</div>

{% else %}
  <h1>Sorry</h1>
{% endif %}

{% endblock %}

blog/templates/blog/view_post.html
{% extends 'blog/base.html' %}

{% load static %}

{% block stylesheet %}
    <link href="{% static 'css/footer.css' %}" rel="stylesheet"/>
{% endblock %}

{% block content %}

{% include 'blog/navbar.html' %}
	<style type="text/css">
		 #image {
        max-width: 400px;
        max-height: 400px;
        margin: 0 auto;
        border-radius: 0px;
    }
    #messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
        }
    #comment-button {
        margin-top: 10px;
    }
    #user-image {
        max-width: 50px;
        max-height: 50px;
    }
	</style>

<div class="container mt-4">
    <div class="row">

        <div class="col-sm-8">
            <!-- Post content-->
            <article>
                <!-- Post header-->
                <header class="mb-4">
                    <!-- Post title-->
                    <h1 class="fw-bolder mb-1 text-capitalize">{{ blog.title }}</h1>
                    <!-- Post meta content-->
                    <div class="text-muted fst-italic mb-2">Posted on {{  blog.date_added }} by <a class="text-reset" href="{% url 'blog:viewotherprofile' blog.author.user.id %}">{{ blog.author }}</a></div>
                    <!-- Post categories-->
                    {% if blog.category != None %}
                        <a class="badge bg-secondary text-decoration-none link-light" href="{% url 'blog:categorydetial' blog.category %}">{{ blog.category }}</a>
                    {% endif %}
                </header>

                {% for message in messages %}
                    <p id="messages" class="badge badge-secondary">{{ message }}</p>
                {% endfor %}
                
                <!-- Preview image figure-->
                <figure class="mb-4"><img class="img-fluid rounded" src="{{ blog.related_image.url }}" alt="..." /></figure>

                <!-- Post content-->
                <section class="mb-5">
                    {% autoescape off %}
                    <p>{{ blog.content | safe }}</p>
                    {% endautoescape %}
                </section>
            </article>

            <form action="{% url 'blog:likepost' blog.pk %}" method="POST">
                {% csrf_token %}
                <button type="submit" name="blog_id" value="{{ blog.id }}" class="btn btn-outline-success btn-sm badge text-body mb-3">Like</button>
            </form>
           
            <span class="small text-dark">{{ total_likes }} likes, {{ blog.comments.count }} comments</span>

            <!-- Comments section-->
            {% if request.user.is_authenticated %}
            <section class="mb-5">
                <div class="card bg-light">
                    <div class="card-body">
                         <h2 class="mb-4">Comments...</h2>
                        <!-- Comment form -->
                        <form class="mb-4" method="POST">
                            {% csrf_token %}
                            {{ form.body | safe }}
                            <button id="comment-button" class="btn btn-primary" type="submit">Comment!</button>
                        </form>

                        <div class="d-flex mb-4">
                            {% if not blog.comments.all %}
                                <p>No comments yet...</p>
                            {% else %}
                             {% for comment in blog.comments.all %}
                        </div>

                        <div class="d-flex mb-4">

                            <div class="flex-shrink-0"><a href="{% url 'blog:viewotherprofile' comment.user.id %}"><img class="rounded-circle" id="user-image" src="{{ comment.user.profile_picture.url }}" alt="{{ comment.user.first_name }}'s picture" /></a></div>

                            <div class="ms-3 text-break">
                                <div class="fw-bold"><a class="text-decoration-none text-body" href="{% url 'blog:viewotherprofile' comment.user.id %}">{{ comment.user }}</a></div>{{ comment.body | safe }}
                                <br>
                                <div class="badge fst-italic mb-2 small bg-secondary">{{ comment.date_added }}</div>
                            </div>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% if request.user.userprofile == blog.author %}
                    <button class="btn btn-outline-warning mt-3"><a href="{% url 'blog:updatepost' blog.id %}" class="text-reset text-decoration-none">Update</a></button>
                    <button class="btn btn-outline-danger mt-3"><a href="{% url 'blog:deletepost' blog.id %}" class="text-reset text-decoration-none">Delete</a></button>
                {% endif %}
            </section>
            {% else %}
            <h4><a class="text-decoration-none text-reset" href="{% url 'registration:login' %}">Login</a> or <a class="text-decoration-none text-reset" href="{% url 'registration:signup' %}">Signup</a> to view more...</h4>
            {% endif %}
         </div>
        {% include 'blog/side_widgets.html' %}
    </div>
</div>
{% include 'blog/footer.html' %}

{% endblock %}